{-# OPTIONS_GHC -fno-warn-unused-imports #-}
#include <bindings.dsl.h>
#include <fluidsynth.h>
module Ensemble.Soundfont.FluidSynth.Foreign.Gen where
import Foreign.Ptr
#strict_import

{- enum fluid_gen_type {
    GEN_STARTADDROFS,
    GEN_ENDADDROFS,
    GEN_STARTLOOPADDROFS,
    GEN_ENDLOOPADDROFS,
    GEN_STARTADDRCOARSEOFS,
    GEN_MODLFOTOPITCH,
    GEN_VIBLFOTOPITCH,
    GEN_MODENVTOPITCH,
    GEN_FILTERFC,
    GEN_FILTERQ,
    GEN_MODLFOTOFILTERFC,
    GEN_MODENVTOFILTERFC,
    GEN_ENDADDRCOARSEOFS,
    GEN_MODLFOTOVOL,
    GEN_UNUSED1,
    GEN_CHORUSSEND,
    GEN_REVERBSEND,
    GEN_PAN,
    GEN_UNUSED2,
    GEN_UNUSED3,
    GEN_UNUSED4,
    GEN_MODLFODELAY,
    GEN_MODLFOFREQ,
    GEN_VIBLFODELAY,
    GEN_VIBLFOFREQ,
    GEN_MODENVDELAY,
    GEN_MODENVATTACK,
    GEN_MODENVHOLD,
    GEN_MODENVDECAY,
    GEN_MODENVSUSTAIN,
    GEN_MODENVRELEASE,
    GEN_KEYTOMODENVHOLD,
    GEN_KEYTOMODENVDECAY,
    GEN_VOLENVDELAY,
    GEN_VOLENVATTACK,
    GEN_VOLENVHOLD,
    GEN_VOLENVDECAY,
    GEN_VOLENVSUSTAIN,
    GEN_VOLENVRELEASE,
    GEN_KEYTOVOLENVHOLD,
    GEN_KEYTOVOLENVDECAY,
    GEN_INSTRUMENT,
    GEN_RESERVED1,
    GEN_KEYRANGE,
    GEN_VELRANGE,
    GEN_STARTLOOPADDRCOARSEOFS,
    GEN_KEYNUM,
    GEN_VELOCITY,
    GEN_ATTENUATION,
    GEN_RESERVED2,
    GEN_ENDLOOPADDRCOARSEOFS,
    GEN_COARSETUNE,
    GEN_FINETUNE,
    GEN_SAMPLEID,
    GEN_SAMPLEMODE,
    GEN_RESERVED3,
    GEN_SCALETUNE,
    GEN_EXCLUSIVECLASS,
    GEN_OVERRIDEROOTKEY,
    GEN_PITCH,
    GEN_CUSTOM_BALANCE,
    GEN_CUSTOM_FILTERFC,
    GEN_CUSTOM_FILTERQ,
    GEN_LAST
}; -}
#integral_t enum fluid_gen_type
#num GEN_STARTADDROFS
#num GEN_ENDADDROFS
#num GEN_STARTLOOPADDROFS
#num GEN_ENDLOOPADDROFS
#num GEN_STARTADDRCOARSEOFS
#num GEN_MODLFOTOPITCH
#num GEN_VIBLFOTOPITCH
#num GEN_MODENVTOPITCH
#num GEN_FILTERFC
#num GEN_FILTERQ
#num GEN_MODLFOTOFILTERFC
#num GEN_MODENVTOFILTERFC
#num GEN_ENDADDRCOARSEOFS
#num GEN_MODLFOTOVOL
#num GEN_UNUSED1
#num GEN_CHORUSSEND
#num GEN_REVERBSEND
#num GEN_PAN
#num GEN_UNUSED2
#num GEN_UNUSED3
#num GEN_UNUSED4
#num GEN_MODLFODELAY
#num GEN_MODLFOFREQ
#num GEN_VIBLFODELAY
#num GEN_VIBLFOFREQ
#num GEN_MODENVDELAY
#num GEN_MODENVATTACK
#num GEN_MODENVHOLD
#num GEN_MODENVDECAY
#num GEN_MODENVSUSTAIN
#num GEN_MODENVRELEASE
#num GEN_KEYTOMODENVHOLD
#num GEN_KEYTOMODENVDECAY
#num GEN_VOLENVDELAY
#num GEN_VOLENVATTACK
#num GEN_VOLENVHOLD
#num GEN_VOLENVDECAY
#num GEN_VOLENVSUSTAIN
#num GEN_VOLENVRELEASE
#num GEN_KEYTOVOLENVHOLD
#num GEN_KEYTOVOLENVDECAY
#num GEN_INSTRUMENT
#num GEN_RESERVED1
#num GEN_KEYRANGE
#num GEN_VELRANGE
#num GEN_STARTLOOPADDRCOARSEOFS
#num GEN_KEYNUM
#num GEN_VELOCITY
#num GEN_ATTENUATION
#num GEN_RESERVED2
#num GEN_ENDLOOPADDRCOARSEOFS
#num GEN_COARSETUNE
#num GEN_FINETUNE
#num GEN_SAMPLEID
#num GEN_SAMPLEMODE
#num GEN_RESERVED3
#num GEN_SCALETUNE
#num GEN_EXCLUSIVECLASS
#num GEN_OVERRIDEROOTKEY
#num GEN_PITCH
#num GEN_CUSTOM_BALANCE
#num GEN_CUSTOM_FILTERFC
#num GEN_CUSTOM_FILTERQ
#num GEN_LAST
