name: Build Windows executable

on: 
  workflow_dispatch:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: jbetz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A projectCross.mingwW64.hsPkgs.ensemble.components.exes.ensemble --keep-going
    - uses: actions/upload-artifact@v3
      with:
        name: ensemble
        path: result
